<a href="https://colab.research.google.com/github/MithunSR/Scipy-Tutorial/blob/main/Scipy_Numerical_Computing_and_Linear_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1.Introduction
Scipy is a powerful library in Python that provides functionalities for numerical computing and linear algebra. It offers a wide range of tools and functions for performing various tasks related to scientific computing, including matrix operations, linear equations solving, eigenvalue and eigenvector computations, matrix decompositions, numerical integration, differentiation, and interpolation. These capabilities make Scipy an essential tool for researchers, engineers, and data scientists working on data analysis, machine learning, and mathematical modeling.

In this code example, we showcase the usage of Scipy for numerical computing tasks using a real-world dataset. We start by loading the California housing dataset, a popular dataset used for regression analysis. We then demonstrate how Scipy can be utilized to perform matrix operations, solve linear equations, find eigenvalues and eigenvectors, perform matrix decompositions, and utilize numerical integration, differentiation, and interpolation.

Throughout the code, we provide step-by-step explanations of each section and highlight the specific functions and methods used for different computations. By going through this example, you will gain a solid understanding of how to leverage Scipy's functionalities for various numerical computing tasks and apply them to real-world datasets.

It's important to note that Scipy is a part of the larger scientific computing ecosystem in Python, which includes other libraries like NumPy, Pandas, and Matplotlib. These libraries complement each other and provide a comprehensive toolkit for scientific computing and data analysis.

#2.Example with code Example
##2.1 Import libraries
numpy (imported as np) for numerical computing.
pandas (imported as pd) for data manipulation and analysis.
scipy.linalg for linear algebra operations.
scipy.integrate.quad for numerical integration.
scipy.misc.derivative for numerical differentiation.
scipy.interpolate.interp1d for interpolation.


In [38]:
import numpy as np
import pandas as pd
from scipy.linalg import lu, qr, svd
from sklearn.datasets import fetch_california_housing
from scipy.integrate import quad
from scipy.misc import derivative
from scipy.interpolate import interp1d

##2.2 Load Dataset
The code uses the fetch_california_housing function from sklearn.datasets to load the California housing dataset.
The dataset is stored in the housing variable, which contains both the data and the target (housing prices).
The data is then converted into a pandas DataFrame (housing_df), and the column names are set using housing.feature_names.
The target variable (housing prices) is added as a new column named "Price" in the DataFrame.


In [39]:
# Load the California housing dataset
housing = fetch_california_housing()
housing_df = pd.DataFrame(housing.data, columns=housing.feature_names)
housing_df['Price'] = housing.target

##2.3 Perform Matrix operation
The code selects the relevant columns ('AveRooms', 'AveBedrms', 'Population') from the housing DataFrame and stores them in the X variable.
The transpose of X is computed using X.T and stored in X_transpose.
The matrix product of X_transpose and X is computed using np.dot(X_transpose, X) and stored in matrix_product.
The matrix inverse of matrix_product is computed using np.linalg.inv(matrix_product) and stored in matrix_inverse.
The determinant of matrix_product is computed using np.linalg.det(matrix_product) and stored in matrix_determinant.

In [40]:
# Perform matrix operations
X = housing_df[['AveRooms', 'AveBedrms', 'Population']].values
X_transpose = X.T
matrix_product = np.dot(X_transpose, X)
matrix_inverse = np.linalg.inv(matrix_product)
matrix_determinant = np.linalg.det(matrix_product)

In [41]:
print("Matrix Operations:")
print("Matrix Product:")
print(matrix_product)
print("Matrix Inverse:")
print(matrix_inverse)
print("Matrix Determinant:")
print(matrix_determinant)

Matrix Operations:
Matrix Product:
[[7.34686462e+05 1.43399883e+05 1.55555196e+08]
 [1.43399883e+05 2.94589973e+04 3.15329544e+07]
 [1.55555196e+08 3.15329544e+07 6.84090565e+10]]
Matrix Inverse:
[[ 2.73784097e-05 -1.31530279e-04 -1.62720548e-09]
 [-1.31530279e-04  6.98898877e-04 -2.30689921e-08]
 [-1.62720548e-09 -2.30689921e-08  2.89516308e-11]]
Matrix Determinant:
3.728978461474487e+19


##2.4 Solving Linear Equations
The code selects the target variable (housing prices) from the housing DataFrame and stores it in the y variable.

The coefficients of the linear equations are computed by solving the equation matrix_product * coefficients = X_transpose * y using np.linalg.solve(matrix_product, np.dot(X_transpose, y)) and stored in the coefficients variable.

In [42]:
# Solve linear equations
y = housing_df['Price'].values
coefficients = np.linalg.solve(matrix_product, np.dot(X_transpose, y))

In [43]:
print("\nLinear Equations:")
print("Coefficients:")
print(coefficients)


Linear Equations:
Coefficients:
[ 4.04008343e-01 -6.98065918e-01  2.83039097e-04]


##2.5 Finding eigenvalues and eigenvectors
The eigenvalues and eigenvectors of matrix_product are computed using np.linalg.eig(matrix_product).
The eigenvalues are stored in the eigenvalues variable, and the eigenvectors are stored in the eigenvectors variable.

In [44]:
# Find eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix_product)

In [45]:
print("\nEigenvalues and Eigenvectors:")
print("Eigenvalues:")
print(eigenvalues)
print("Eigenvectors:")
print(eigenvectors)


Eigenvalues and Eigenvectors:
Eigenvalues:
[6.84094247e+10 3.94510003e+05 1.38170687e+03]
Eigenvectors:
[[ 2.27390473e-03  9.82622799e-01  1.85599742e-01]
 [ 4.60948317e-04  1.85599172e-01 -9.82625430e-01]
 [ 9.99997308e-01 -2.31994850e-03  3.09034911e-05]]


##2.6 Performing LU decomposition
The LU decomposition of matrix_product is performed using scipy.linalg.lu(matrix_product).
The permutation matrix P, lower triangular matrix L, and upper triangular matrix U are obtained and stored in P, L, and U variables, respectively.

In [46]:
# Perform LU decomposition
P, L, U = lu(matrix_product)

In [47]:
print("\nLU Decomposition:")
print("P:")
print(P)
print("L:")
print(L)
print("U:")
print(U)


LU Decomposition:
P:
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
L:
[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 4.72299531e-03  1.00000000e+00  0.00000000e+00]
 [ 9.21858520e-04 -7.05364794e-02  1.00000000e+00]]
U:
[[ 1.55555196e+08  3.15329544e+07  6.84090565e+10]
 [ 0.00000000e+00 -5.53011256e+03 -1.67540456e+08]
 [ 0.00000000e+00  0.00000000e+00 -4.33482311e+07]]


##2.7 Performing QR decomposition
The QR decomposition of matrix_product is performed using scipy.linalg.qr(matrix_product).
The orthogonal matrix Q and upper triangular matrix R are obtained and stored in Q and R variables, respectively.

In [48]:
# Perform QR decomposition
Q, R = qr(matrix_product)

In [49]:
print("\nQR Decomposition:")
print("Q:")
print(Q)
print("R:")
print(R)


QR Decomposition:
Q:
[[-4.72294063e-03  9.97510370e-01 -7.03616030e-02]
 [-9.21847847e-04 -7.03667009e-02 -9.97520765e-01]
 [-9.99988422e-01 -4.64636866e-03  1.25189054e-03]]
R:
[[-1.55556997e+08 -3.15332937e+07 -6.84090282e+10]
 [ 0.00000000e+00 -5.54379290e+03 -1.64904644e+08]
 [ 0.00000000e+00  0.00000000e+00  4.32407607e+07]]


##2.8 Performing singular value decomposition (SVD)
The singular value decomposition of matrix_product is performed using scipy.linalg.svd(matrix_product).
The matrices U, S, and V are obtained and stored in U, S, and V variables, respectively.

In [50]:
# Perform singular value decomposition (SVD)
U, S, V = svd(matrix_product)

In [51]:
print("\nSingular Value Decomposition:")
print("U:")
print(U)
print("S:")
print(S)
print("V:")
print(V)


Singular Value Decomposition:
U:
[[-2.27390473e-03 -9.82622799e-01 -1.85599742e-01]
 [-4.60948317e-04 -1.85599172e-01  9.82625430e-01]
 [-9.99997308e-01  2.31994850e-03 -3.09034911e-05]]
S:
[6.84094247e+10 3.94510003e+05 1.38170687e+03]
V:
[[-2.27390473e-03 -4.60948317e-04 -9.99997308e-01]
 [-9.82622799e-01 -1.85599172e-01  2.31994850e-03]
 [-1.85599742e-01  9.82625430e-01 -3.09034911e-05]]


##2.9 Numerical integration
The code defines a function f(x) to be integrated (x^2 in this case).
The numerical integration of f over the interval [0, 5] is performed using scipy.integrate.quad(f, 0, 5).
The computed area under the curve and the estimated error are stored in area and error variables, respectively.

In [52]:
# Define a function for integration
def f(x):
    return x**2

# Perform numerical integration
area, error = quad(f, 0, 5)


In [53]:
print("\nNumerical Integration:")
print("Area under the Curve:")
print(area)


Numerical Integration:
Area under the Curve:
41.66666666666666


##2.10 Numerical differentiation:

The code defines a function g(x) to be differentiated (x^3 in this case).
The numerical differentiation of g at x = 2.0 is performed using scipy.misc.derivative(g, 2.0).
The computed derivative result is stored in the derivative_result variable.

In [54]:
# Define a function for differentiation
def g(x):
    return x**3

# Perform numerical differentiation
derivative_result = derivative(g, 2.0)

<ipython-input-54-3d718bfa6e5e>:6: DeprecationWarning: scipy.misc.derivative is deprecated in SciPy v1.10.0; and will be completely removed in SciPy v1.12.0. You may consider using findiff: https://github.com/maroba/findiff or numdifftools: https://github.com/pbrod/numdifftools
  derivative_result = derivative(g, 2.0)


In [55]:
print("\nNumerical Differentiation:")
print("Derivative Result:")
print(derivative_result)


Numerical Differentiation:
Derivative Result:
13.0


##2.11 Interpolation:

The code creates sample data (x and y) for interpolation.
The interp1d function from scipy.interpolate is used to perform cubic interpolation on the data.
Interpolated values are generated for x_interpolated using the interpolated function f.
The interpolated values are stored in the y_interpolated variable.

In [56]:




# Create sample data for interpolation
x = np.linspace(0, 10, num=11, endpoint=True)
y = np.cos(-x**2/9.0)

# Perform interpolation
f = interp1d(x, y, kind='cubic')

# Generate interpolated values
x_interpolated = np.linspace(0, 10, num=41, endpoint=True)
y_interpolated = f(x_interpolated)


print("\nInterpolation:")
print("Interpolated Values:")
print(list(zip(x_interpolated, y_interpolated)))



Interpolation:
Interpolated Values:
[(0.0, 1.0), (0.25, 0.9964109904444228), (0.5, 0.996091479261226), (0.75, 0.9961846055821391), (1.0, 0.993833508538892), (1.25, 0.9861813272632147), (1.5, 0.9703712008868367), (1.75, 0.9435462685414884), (2.0, 0.9028496693588987), (2.25, 0.84536349432982), (2.5, 0.7679256418810922), (2.75, 0.6673129622985782), (3.0, 0.5403023058681398), (3.25, 0.38508734103575576), (3.5, 0.2055290088878708), (3.75, 0.006905068671045914), (4.0, -0.2055067203681578), (4.25, -0.4240390513971404), (4.5, -0.631466427239146), (4.75, -0.8081738031313802), (5.0, -0.9345461343110483), (5.25, -0.9926755557687218), (5.5, -0.9714829215084378), (5.75, -0.8615962652876001), (6.0, -0.653643620863612), (6.25, -0.34884468229586846), (6.5, 0.00921421514827031), (6.75, 0.3663550758994522), (7.0, 0.6683999043883257), (7.25, 0.8679573603148192), (7.5, 0.9447827244559819), (7.75, 0.8854179328581436), (8.0, 0.6764049215676338), (8.25, 0.32013188190749836), (8.5, -0.11762797369235069), (8.